# Generated by Django 3.1.7 on 2021-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210324_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='ans_text',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=50),
        ),
    ]
