# Generated by Django 3.1.7 on 2021-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20210326_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='ans_text',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('UNK', 'UNK')], default=None, max_length=50),
        ),
    ]
