# Generated by Django 3.1.6 on 2021-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20210329_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='ans_text',
            field=models.CharField(max_length=200),
        ),
    ]
