# Generated by Django 3.1.6 on 2021-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20210522_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
