# Generated by Django 3.2.3 on 2021-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_auto_20210605_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
